[build]
  base = "my-portfolio"
  command = "npm run build"
  publish = "build" # ¡CAMBIA ESTO! Debe ser "build", no "my-portfolio/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200