const DataProyectos = [
  {
    id: 'impresion-3d-1',
    title: 'Impresión 3D: Prototipado Rápido',
    tagline: 'Transformando ideas en objetos tangibles.',
    description: 'Este proyecto se centró en el prototipado rápido y la fabricación de piezas personalizadas utilizando tecnología de impresión 3D FDM. Exploramos el diseño paramétrico y la optimización de geometrías para la funcionalidad y la estética.',
    problem: 'La necesidad de crear prototipos funcionales y económicos en poco tiempo para validar conceptos de diseño y reducir los ciclos de desarrollo de productos.',
    solution: 'Implementamos un flujo de trabajo ágil desde el modelado 3D (CAD) hasta la impresión, seleccionando materiales apropiados (PLA, PETG) y optimizando los parámetros de impresión para cada caso específico.',
    moodboard: null,
    wireframes: [],
    finalDesign: [
      '/Imagenes/Proyecto1/3-1.png',
      '/Imagenes/Proyecto1/Impresion.png',
    ],
    colors: {
      'Primario': '#3498DB',
      'Secundario': '#E74C3C',
      'Acento': '#2ECC71',
    },
    typography: {
      'Título': 'Roboto, sans-serif',
      'Cuerpo': 'Open Sans, sans-serif',
    },
    technologies: ['Fusion 360', 'PrusaSlicer', 'Impresoras FDM'],
    myRole: 'Diseñador 3D, Operador de Impresora 3D, Post-procesado.',
    liveDemo: null,
    repoUrl: null,
  },
  {
    id: 'diseño-web-landing',
    title: 'Diseño de Landing Page para Startup',
    tagline: 'Una primera impresión impactante para un nuevo negocio.',
    description: 'Diseño de una landing page moderna y responsive para una startup tecnológica, enfocada en la conversión de visitantes a usuarios registrados.',
    problem: 'La startup necesitaba una presencia online efectiva y visualmente atractiva para presentar su producto y captar los primeros usuarios de forma rápida.',
    solution: 'Diseñé una interfaz limpia y minimalista, con un claro llamado a la acción (CTA) y elementos visuales que comunican eficazmente la propuesta de valor del producto. Se realizó investigación de usuario para definir la arquitectura de la información.',
    moodboard: '/Imagenes/Proyecto2/moodboard_web.jpg',
    wireframes: [
      '/Imagenes/Proyecto2/wireframe_desktop.png',
      '/Imagenes/Proyecto2/wireframe_mobile.png',
    ],
    finalDesign: [
      '/Imagenes/Proyecto2/desktop_final.png',
      '/Imagenes/Proyecto2/mobile_final.png',
    ],
    colors: {
      'Primario': '#4A90E2',
      'Acento': '#7ED321',
      'Fondo Claro': '#F9F9F9',
      'Texto Oscuro': '#333333',
    },
    typography: {
      'Encabezados': 'Montserrat, sans-serif',
      'Párrafos': 'Lato, sans-serif',
    },
    technologies: ['Figma', 'Adobe XD', 'Illustrator'],
    myRole: 'Diseñador UI/UX, Investigador de Usuario.',
    repoUrl: null,
  },
  {
    id: 'impresion-3d-2',
    title: 'Impresión 3D: Prototipado Rápido',
    tagline: 'Transformando ideas en objetos tangibles.',
    description: 'Este proyecto se centró en el prototipado rápido y la fabricación de piezas personalizadas utilizando tecnología de impresión 3D FDM. Exploramos el diseño paramétrico y la optimización de geometrías para la funcionalidad y la estética.',
    problem: 'La necesidad de crear prototipos funcionales y económicos en poco tiempo para validar conceptos de diseño y reducir los ciclos de desarrollo de productos.',
    solution: 'Implementamos un flujo de trabajo ágil desde el modelado 3D (CAD) hasta la impresión, seleccionando materiales apropiados (PLA, PETG) y optimizando los parámetros de impresión para cada caso específico.',
    moodboard: null,
    wireframes: [],
    finalDesign: [
      '/Imagenes/Proyecto1/3-1.png',
      '/Imagenes/Proyecto1/Impresion.png',
    ],
    colors: {
      'Primario': '#3498DB',
      'Secundario': '#E74C3C',
      'Acento': '#2ECC71',
    },
    typography: {
      'Título': 'Roboto, sans-serif',
      'Cuerpo': 'Open Sans, sans-serif',
    },
    technologies: ['Fusion 360', 'PrusaSlicer', 'Impresoras FDM'],
    myRole: 'Diseñador 3D, Operador de Impresora 3D, Post-procesado.',
    liveDemo: null,
    repoUrl: null,
  },
  {
    id: 'impresion-3d-3',
    title: 'Impresión 3D: Prototipado Rápido',
    tagline: 'Transformando ideas en objetos tangibles.',
    description: 'Este proyecto se centró en el prototipado rápido y la fabricación de piezas personalizadas utilizando tecnología de impresión 3D FDM. Exploramos el diseño paramétrico y la optimización de geometrías para la funcionalidad y la estética.',
    problem: 'La necesidad de crear prototipos funcionales y económicos en poco tiempo para validar conceptos de diseño y reducir los ciclos de desarrollo de productos.',
    solution: 'Implementamos un flujo de trabajo ágil desde el modelado 3D (CAD) hasta la impresión, seleccionando materiales apropiados (PLA, PETG) y optimizando los parámetros de impresión para cada caso específico.',
    moodboard: null,
    wireframes: [],
    finalDesign: [
      '/Imagenes/Proyecto1/3-1.png',
      '/Imagenes/Proyecto1/Impresion.png',
    ],
    colors: {
      'Primario': '#3498DB',
      'Secundario': '#E74C3C',
      'Acento': '#2ECC71',
    },
    typography: {
      'Título': 'Roboto, sans-serif',
      'Cuerpo': 'Open Sans, sans-serif',
    },
    technologies: ['Fusion 360', 'PrusaSlicer', 'Impresoras FDM'],
    myRole: 'Diseñador 3D, Operador de Impresora 3D, Post-procesado.',
    liveDemo: null,
    repoUrl: null,
  },
  {
    id: 'impresion-3d-4',
    title: 'Impresión 3D: Prototipado Rápido',
    tagline: 'Transformando ideas en objetos tangibles.',
    description: 'Este proyecto se centró en el prototipado rápido y la fabricación de piezas personalizadas utilizando tecnología de impresión 3D FDM. Exploramos el diseño paramétrico y la optimización de geometrías para la funcionalidad y la estética.',
    problem: 'La necesidad de crear prototipos funcionales y económicos en poco tiempo para validar conceptos de diseño y reducir los ciclos de desarrollo de productos.',
    solution: 'Implementamos un flujo de trabajo ágil desde el modelado 3D (CAD) hasta la impresión, seleccionando materiales apropiados (PLA, PETG) y optimizando los parámetros de impresión para cada caso específico.',
    moodboard: null,
    wireframes: [],
    finalDesign: [
      '/Imagenes/Proyecto1/3-1.png',
      '/Imagenes/Proyecto1/Impresion.png',
    ],
    colors: {
      'Primario': '#3498DB',
      'Secundario': '#E74C3C',
      'Acento': '#2ECC71',
    },
    typography: {
      'Título': 'Roboto, sans-serif',
      'Cuerpo': 'Open Sans, sans-serif',
    },
    technologies: ['Fusion 360', 'PrusaSlicer', 'Impresoras FDM'],
    myRole: 'Diseñador 3D, Operador de Impresora 3D, Post-procesado.',
    liveDemo: null,
    repoUrl: null,
  },
  {
    id: 'impresion-3d-5',
    title: 'Impresión 3D: Prototipado Rápido',
    tagline: 'Transformando ideas en objetos tangibles.',
    description: 'Este proyecto se centró en el prototipado rápido y la fabricación de piezas personalizadas utilizando tecnología de impresión 3D FDM. Exploramos el diseño paramétrico y la optimización de geometrías para la funcionalidad y la estética.',
    problem: 'La necesidad de crear prototipos funcionales y económicos en poco tiempo para validar conceptos de diseño y reducir los ciclos de desarrollo de productos.',
    solution: 'Implementamos un flujo de trabajo ágil desde el modelado 3D (CAD) hasta la impresión, seleccionando materiales apropiados (PLA, PETG) y optimizando los parámetros de impresión para cada caso específico.',
    moodboard: null,
    wireframes: [],
    finalDesign: [
      '/Imagenes/Proyecto1/3-1.png',
      '/Imagenes/Proyecto1/Impresion.png',
    ],
    colors: {
      'Primario': '#3498DB',
      'Secundario': '#E74C3C',
      'Acento': '#2ECC71',
    },
    typography: {
      'Título': 'Roboto, sans-serif',
      'Cuerpo': 'Open Sans, sans-serif',
    },
    technologies: ['Fusion 360', 'PrusaSlicer', 'Impresoras FDM'],
    myRole: 'Diseñador 3D, Operador de Impresora 3D, Post-procesado.',
    liveDemo: null,
    repoUrl: null,
  },
];

export default DataProyectos;